[project]
name = "crypto-trend-crew-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=0.130.0",
    "crewai-tools>=0.47.1",
    "requests>=2.32.4",
]
